### ISSUE TITLE
Issue in running the project

### ISSUE THREAD

**Issue by parniantaghipour** [yuanhunglo/pair#4]
Hi, 
I am new to ML systems, but when I tried to run your project I got the following error. Can you help me to fix it.
I am not using GPU and I do not have SSD.
==> Embedding error: ('Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=\narray([[[[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        ...,\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]]]], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]',)
==> Embedding error: ('Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=\narray([[[[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        ...,\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]]]], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]',)
==> Embedding error: ('Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=\narray([[[[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        ...,\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]],\n\n        [[151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         ...,\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ],\n         [151.061  , 138.22101, 131.32   ]]]], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]',)
Traceback (most recent call last):
  File "run_pair.py", line 82, in <module>
    main()
  File "run_pair.py", line 51, in main
    layer_range=cfg['LAYER_NAMES'])
  File "/home/parnian/PycharmProjects/pair/pair/pair/style_stack.py", line 221, in build
    inst._build_index(lib_path)
  File "/home/parnian/PycharmProjects/pair/pair/pair/style_stack.py", line 520, in _build_index
    self._index_vectors()
  File "/home/parnian/PycharmProjects/pair/pair/pair/style_stack.py", line 539, in _index_vectors
    gram_block = np.stack(gram_list)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/parnian/PycharmProjects/pair/venv/lib/python3.6/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
Thank you in advance.

**Comment by daliaMarzouk90** [comment]
Hello,

I have the same issue.
If there is any solution?
